### ISSUE TITLE
Easier feedback loop

### ISSUE THREAD

**Issue by ofek** [hynek/hatch-fancy-pypi-readme#18]
If you want to reduce what you have to maintain, Hatch now can replace the CLI here https://hatch.pypa.io/latest/blog/2022/10/08/hatch-v160/#project-metadata

**Comment by hynek** [comment]
That's cool and (probably?) solves https://github.com/pypa/hatch/issues/442 – could you optionally disable the rendering with rich? Sometimes I want to see the raw text. I could always pipe it into rich myself, but not the other way.

**Comment by ofek** [comment]
> solves https://github.com/pypa/hatch/issues/442

Non-build plugins is still unsolved, for now

> could you optionally disable the rendering with rich? Sometimes I want to see the raw text

You could not provide a argument and pipe the json to jq

**Comment by hynek** [comment]
> > solves https://github.com/pypa/hatch/issues/442
> Non-build plugins is still unsolved, for now

As in "metadata aren't supported"? I guess I'll have to keep maintaining until it is then.

> You could not provide a argument and pipe the json to jq

Maybe worth documenting.

**Comment by ofek** [comment]
Hatch is unsolved https://hatch.pypa.io/latest/plugins/about/#types

> Maybe worth documenting

ok 👍

**Comment by ofek** [comment]
- https://hatch.pypa.io/dev/cli/reference/#hatch-project-metadata
- https://github.com/Textualize/rich/issues/2585
