### ISSUE TITLE
This package has completely broken my installation of an otherwise fine chain of python2 packages.

### ISSUE THREAD

**Issue by gllxflr** [hynek/hatch-fancy-pypi-readme#43]
Please add a version with support for python2. Some packages relying on this package do ship 2.7-compatible source, but include this project, which ruins the whole chain. I'm trying to install a piece of software, but this, that shouldn't even affect the building of it, has completely prevented that from happening.

**Comment by hynek** [comment]
I'm sorry for your build chain, but *hatch-fancy-pypi-readme* is just the first symptom of a bigger problem.

If you want to use a Python version that has been officially EOL'd more than 4 years ago, you're gonna have to pin your dependencies or pay [someone](https://www.activestate.com/products/python/python-2-7/) to make it work.
