### ISSUE TITLE
Is it intended to install AUTHORS.md as license file?

### ISSUE THREAD

**Issue by pnemade** [hynek/hatch-fancy-pypi-readme#8]
I am packaging this module in Fedora. During its rpm packaging, fedora-review tool found that this module is installing AUTHORS.md file as /usr/lib/python3.11/site-packages/hatch_fancy_pypi_readme-22.3.0.dist-info/licenses/AUTHORS.md

But this is not a license file. Can this be corrected?

**Comment by hynek** [comment]
This is standard wheel behavior:

https://github.com/pypa/wheel/blob/5edc61d2c6535c380fa278bc83c578fbd5444167/src/wheel/bdist_wheel.py#L450

If it makes you feel any better, I can mention the license in that file. But if you object to this in general, I guess you'll have to take it to wheel or in your macros?

**Comment by penguinpee** [comment]
This is more a convenience feature of wheel. You can also explicitly define your [`license_files`](https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file).

Right now there's now licensing information in `AUTHORS.md` but it is being installed in `licenses`.

**Comment by ofek** [comment]
Hatch follows PEP 639:

- https://peps.python.org/pep-0639/#add-license-files-key
- https://github.com/pypa/hatch/blob/hatchling-v1.8.1/backend/src/hatchling/metadata/core.py#L587-L588

**Comment by pnemade** [comment]
Thank you all for your comments

@hynek I understood this now.  I see then no fix required here.

Thank you.

**Comment by penguinpee** [comment]
> > This is more a convenience feature of wheel. You can also explicitly define your [`license_files`](https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file).
> > Right now there's now licensing information in `AUTHORS.md` but it is being installed in `licenses`.
> 
> Yes, but that is something to take up with wheel and/or PyPA.
> 
> As Ofek mentioned, it does what it's supposed to and so does this project:
> 
> https://github.com/hynek/hatch-fancy-pypi-readme/blob/56d3161e1fcb414187c92ab57946715caf51a114/pyproject.toml#L13

I wasn't implying that this project is not following the defined standards. But there's control you can leverage in the `pyproject.toml` file:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index fc98a2e..2ebf7ff 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -33,6 +33,9 @@ dependencies = [
   "typing-extensions; python_version<'3.8'",
 ]
 
+[project.license-files]
+paths = ["LICENSE.txt"]
+
 [project.readme]
 content-type = "text/markdown"
 text = """*hatch-fancy-pypi-readme* is an MIT-licensed metadata plugin for [*Hatch*](https://hatch.pypa.io/).
```

This will add the file to the source distribution archive, but not install it. Just like what is done with the README.md file.

> Also I've added licensing information to AUTHORS.md which makes it grey area. upside_down_face

That's putting the cart before the horse. _Das Pferd von hinten aufzäumen_, as they say in your neck of the woods.

Just my $0.02...

**Comment by tiran** [comment]
Fellow Fedora packager here.

I suggest that you bring this up with Fedora's Python maintenance team (e.g. @hroncok). The RPM packaging macros for PyPI packages should be updated to handle `AUTHOR*` as `%doc` files instead of `%license` files *iff* there is another license file. No need to annoy upstream packagers with our downstream problems. :)

**Comment by hroncok** [comment]
The Python packaging macros can only follow existing standards/tech. Iff the file is marked as license-file in core metadata, we mark it as license in RPM metadata. If it is not, we do not. There's no such thing as documentation-file in core metadata (yet?), so we don't mark anything as %doc. No guessing, no heuristic. Sorry. Anyway I agree that we should not bother upstream projects (other than wheel) with this.
